"""Shared constants for agent tools modules."""

# Retrieval limits
MAX_RETRIEVAL_RESULTS = 10

# Validation thresholds
MIN_RESPONSE_LENGTH = 50
CONFIDENCE_REDUCTION_INCOMPLETE = 0.8
CONFIDENCE_REDUCTION_NO_SOURCE = 0.7
CONFIDENCE_REDUCTION_NO_SOURCES = 0.6
CONFIDENCE_REDUCTION_HALLUCINATION = 0.5
CONFIDENCE_REDUCTION_COHERENCE = 0.9
RELEVANCE_THRESHOLD = 0.3
ACCEPT_CONFIDENCE_THRESHOLD = 0.8
REFINE_CONFIDENCE_THRESHOLD = 0.6
VALIDATION_CONFIDENCE_THRESHOLD = 0.6
# Consider a source sufficiently referenced when >=4 words overlap
MAX_SENTENCE_WORD_OVERLAP = 4
MIN_AVG_SENTENCE_LENGTH = 3
MAX_AVG_SENTENCE_LENGTH = 50
MAX_ISSUES_FOR_ACCEPT = 1
FIRST_N_SOURCES_CHECK = 3
